[package]
name = "petrovich"
version = "0.1.0"
authors = ["devrtc0 <azat.mirzaianov@gmail.com>"]
edition = "2018"

[dependencies]
petrovich_core = { path = "../core" }
gtk = { version = "0.9", default-features = false }
gio = { version = "0.9", default-features = false }
